name: hello-world

on: push

jobs:
  hello-world-joob:
    
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
